
server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ssosys?useUnicode=true&useSSL=false
    username: root
    password: yyf_yes

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false

  http:
    encoding:
      charset: utf-8
      enabled: true

  #热部署
  devtools:
    restart:
      enabled: true


logging:
  config: classpath:logback-spring.xml

